[book]
authors = ["Jacob Morgan"]
language = "en"
multilingual = false
src = "docs/"
title = "Shoebox Docs"

[rust]
edition = "2021"

[build]
build-dir = "site"


[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/slackspace-io/shoebox"
highlight-code = true
