[database]
database_ip = "127.0.0.1"
database_port = "5432"
database_name = "shoebox-dev"
database_user = "shoebox"
database_password = "shoebox"



[[paths]]
root_path = "/mnt/storage/tove/immich/auto-transcoded/"
name = "videos"
description = "Bmpcc transcoded videos"


[immich]
server_url = "https://immich.your.domain"


#[[paths]]
#root_path = "/mnt/immich/app/upload/library/Jacob/"
#name = "my_phone"
#description = "My phone photos"

