[database]
database_ip_port = "127.0.0.1:5432"
database_name = "shoebox"


[[paths]]
root_path = "/mnt/storage/tove/immich/auto-transcoded/"
name = "videos"
description = "Bmpcc transcoded videos"


[[paths]]
root_path = "/mnt/immich/app/upload/library/Jacob/"
name = "my_phone"
description = "My phone photos"

