apiVersion: v2
name: shoebox
description: A Helm chart for the Shoebox application - a digital shoebox for your videos
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - video
  - organizer
  - shoebox
  - archive
maintainers:
  - name: Shoebox Team
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
