name: Release Charts

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
      - '.github/workflows/helm-release.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'charts/**'

concurrency:
  group: "shoebox-helm"
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    container: quay.io/helmpack/chart-testing
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: videos
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #- name: Add Bitnami repository
      #  run: helm repo add bitnami https://charts.bitnami.com/bitnami

      #- name: Update Helm repositories
      #  run: helm repo update

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --charts charts/shoebox --validate-maintainers=false

      #- name: Add Helm repositories
      #  run: |
      #    helm repo add bitnami https://charts.bitnami.com/bitnami
      #    helm repo update

      - name: Run chart-testing (install)
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --charts charts/shoebox --helm-extra-set-args "--set persistence.data.enabled=false --set persistence.thumbnails.enabled=false --set persistence.exports.enabled=false --set config.mediaSourcePaths.enabled=false --set config.databaseUrl=postgres://postgres:postgres@localhost:5432/videos"

  release:
    needs: lint-test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Add Bitnami repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Update Helm repositories
        run: helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          pages_branch: main
        env:
          CR_TOKEN: "${{ github.token }}"
