name: Build and Push Shoebox Image

on:
  push:
    branches:
      - main

    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'assets/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/shoebox.yml'

concurrency:
  group: "shoebox"
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/slackspace-io/shoebox:preview,ghcr.io/slackspace-io/shoebox:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/slackspace-io/shoebox:pr-build-cache
          cache-to: type=registry,ref=ghcr.io/slackspace-io/shoebox:pr-build-cache,mode=max
